[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]
cmds = ["corepack enable && corepack prepare pnpm@latest --activate"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["npx prisma generate", "pnpm run build"]

[start]
cmd = "node dist/index.js"
